{% set version = '0.1.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-interleave
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/interleave_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/interleave/interleave_{{ version }}.tar.gz
  sha256: fa67491d03ca81898afc5df75fc50ef067bee79906b8c7617c8a0c1da61e6a25

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-geometries                 # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-geometries >=0.2.4
  run:
    - r-base
    - r-rcpp
    - r-geometries >=0.2.4

test:
  commands:
    - $R -e "library('interleave')"           # [not win]
    - "\"%R%\" -e \"library('interleave')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=interleave
  license: MIT
  summary: Converts matrices and lists of matrices into a single vector by interleaving their
    values. That is, each element of the result vector is filled from the input matrices
    one row at a time. This is the same as transposing a matrix, then removing the dimension
    attribute, but is designed to operate on matrices in nested list structures.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: interleave
# Type: Package
# Title: Converts Tabular Data to Interleaved Vectors
# Version: 0.1.2
# Date: 2024-01-18
# Authors@R: c( person("David", "Cooley", email = "david.cooley.au@gmail.com", role = c("aut", "cre")), person("Mapbox", role = "cph", comment = "author of header library earcut.hpp") )
# Description: Converts matrices and lists of matrices into a single vector by interleaving their values. That is, each element of the result vector is filled from the input matrices one row at a time. This is the same as transposing a matrix, then removing the dimension attribute, but is designed to operate on matrices in nested list structures.
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Depends: R (>= 3.0.2)
# LinkingTo: geometries (>= 0.2.4), Rcpp
# Imports: Rcpp
# Suggests: covr, sfheaders, tinytest
# NeedsCompilation: yes
# Packaged: 2024-01-17 23:38:07 UTC; dave
# Author: David Cooley [aut, cre], Mapbox [cph] (author of header library earcut.hpp)
# Maintainer: David Cooley <david.cooley.au@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-01-17 23:50:02 UTC
